Aplicação Web: Marvel Strike Team
Annalgc/challenge-frontend-react pull request #1
Opened 2021-07-12 18:52 UTC by Annalgc

## Introdução
A aplicação foi desenvolvida baseada no desafio da Live On para reconhecimento de habilidades e conhecimentos técnicos.

- [Protótipo](https://www.figma.com/file/b7EzpqbYSCIjj2OFHPGCqY/Live-On---Challenge-Frontend-React)
- [Card no Jira (LFE-219)](https://liveonsolutions.atlassian.net/jira/software/projects/LFE/boards/51?selectedIssue=LFE-219)

## Tipo das modificações
Que tipo de mudança você está trazendo ao Challenge Frontend Marvel?
Coloque um _x_ nas caixinhas que se aplicam:

 - [ ] Melhorias ou refatoração (alterações em código não-críticas);
 - [ ] Style (alterações no estilo de uma funcionalidade);
 - [ ] Bugfix (mudança não-crítica que corrige um bug);
 - [x] Feature (mudança não-crítica que adiciona uma funcionalidade);
 - [ ] Mudança crítica (fix ou feature que pode causar problemas em funcionalidades já existentes);
 - [ ] Documentações (caso seja uma documentação ou nenhuma das outras opções se aplique);

2021-07-22 13:01 UTC, hurick requested changes
@Annalgc comentários sobre o código 👇🏻

2021-07-22 13:01 UTC, hurick commented on src/pages/Profile/index.jsx
> +        .catch(error => {
@Annalgc o importante do `.catch` é que ele não é um método apenas para tratar e exibir erros para o desenvolvedor, mas também para o usuário.

Recomendo muito que você faça um tratamento, adicione um toast ou algo do tipo avisando ao usuário que um erro aconteceu com a chamada da API, visto que é a única forma de ele entender o que está acontecendo..

2021-07-22 13:01 UTC, hurick commented on src/pages/Profile/index.jsx
> +          console.log('erro: ', error)
@Annalgc o importante do `.catch` é que ele não é um método apenas para tratar e exibir erros para o desenvolvedor, mas também para o usuário.

Recomendo muito que você faça um tratamento, adicione um toast ou algo do tipo avisando ao usuário que um erro aconteceu com a chamada da API, visto que é a única forma de ele entender o que está acontecendo..

2021-07-22 13:41 UTC, Annalgc commented on src/Routes/index.js
> +export const Routes = (props) => {
Entendido! Colocarei isso em prática.

2021-07-23 04:19 UTC, Annalgc commented on .env.example
> +REACT_APP_PUBLIC_KEY = '2244a307f79a1950202dabda8b4cdb17'
Entendi! Não tenho costume de deixar repositórios abertos, então seguindo o padrão, deixarei este também privado.

2021-07-23 04:20 UTC, Annalgc commented on README.md
> +# **Marvel Strike Team**
Obrigada pelo feedback!

2021-07-23 04:20 UTC, Annalgc commented on package.json
> +    "eject": "react-scripts eject"
Entendido! Estarei utilizando esse padrão de exclusão nos próximos projetos.

2021-07-23 04:24 UTC, Annalgc commented on public/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
Isso vem do próprio Google Fonts quando importamos a font, acredita? Nem foi proposital tê-lo aí. De qualquer forma, seguirei o mesmo padrão nos próximos. Aliás, dei uma pesquisada no que isso poderia impactar, e realmente é de extrema importância ter o atributo declarado, uma vez que pode ter problemas com o não carregamento da font né?!

2021-07-23 04:26 UTC, Annalgc commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
Na época, surgiram dúvidas, pesquisei, apesar de saber que engloba rastreamento e evita a sobrecarga da página, o conceito ainda é um pouco abstrato. Se puder dar uma explicada um pouco menos informal..

2021-07-23 04:27 UTC, Annalgc commented on public/manifest.json
> +{
Carrega em si os metadados do projeto né? Ex.: Versão, biblioteca utilizada.

2021-07-23 04:29 UTC, Annalgc commented on src/components/CardHeroItem/index.jsx
> +} from './styles.js';
Entendido! Colocarei isso em prática.

2021-07-23 04:29 UTC, Annalgc commented on src/components/CardHeroItem/index.jsx
> +  }, [])
Opa, foi mal! Arrumei. Obrigada!

2021-07-23 04:31 UTC, Annalgc commented on src/components/CardHeroItem/index.jsx
> +  const handleAddFavoriteHero = hero => {
Perfeito! Fiz a mudança, porém, não levei a `handleToggleTeam` pra dentro do arquivo `heroFavorite.js`, pois ela controla o estado do componente pra poder chamar às funções de acordo. Se tiver alguma sugestão, posso tentar aplicá-la.

2021-07-23 04:33 UTC, Annalgc commented on src/components/ComicItem/index.jsx
> +  const pricesFind = (price) => {
Beleza! Vou colocar mais em prática esse modelo mais curto nas funções que possuem retorno direto.

2021-07-23 04:35 UTC, Annalgc commented on src/components/CardHeroItem/index.jsx
> +        <Link to={`/profile/${id}`} className='cardHero'>
Hum.. Entendido! Na realidade, foi mais uma má interpretação minha mesmo, quando surgiu a ideia de usar single quotes em JavaScript, acabei enfiando em tudo. Obrigada pelo feedback!

2021-07-23 04:36 UTC, Annalgc commented on src/components/Cover/index.jsx
> +export const Cover = (props) => {
Perfeito! Só uma dúvida, por que encapsulá-lo com chaves? Uma vez que não recebo objetos..

2021-07-23 04:41 UTC, Annalgc commented on src/components/Footer/index.jsx
> +      <span className='developerText'>Developed by <a className="pageLink" href='https://github.com/Annalgc' target='blank'>Anna Luiza</a></span>
Entendido! Na realidade, tive um problema de atributos com o eslint quando coloquei o underline. Agora com esse feedback, fiz dessa forma e fui atrás de saber pra que o tal do atributo `noreferrer` e soube que pode até gerar problemas de segurança se ele não for declarado.

[Link Types - Noreferrer](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer)

2021-07-23 04:43 UTC, Annalgc commented on src/components/HeroProfile/index.jsx
> +          <p className='cTexts__description'>{description ? description : 'Description Unavaible.'}</p>
Nice! Obrigada pelo feedback!

2021-07-23 04:45 UTC, Annalgc commented on src/components/Paginate/index.jsx
> +export const Paginate = ({...rest}) => {
Então, fiz baseado na documentação do componente.. Acabei fazendo alguns testes e sem o spread operator, ele não atualiza a página, ele fica estático como se ainda tivesse na página 1. 
Talvez o spread operator neste caso, seja pra ele identificar que mudamos a página, trazendo os próximos conteúdos.

2021-07-23 04:46 UTC, Annalgc commented on src/pages/Favorites/index.jsx
> +export default Favorites
Opa! Foi mal, deve ter ficado pra trás quando fiz as mudanças para `named export`.

2021-07-23 04:52 UTC, Annalgc commented on src/pages/Home/index.jsx
> +        setTotalPerPage(Math.ceil(response.total / 20))
Neste caso, suponhamos que existe uma sobra de conteúdo a ser exibido, como estamos fazendo uma divisão, dependendo da quantidade de conteúdos, o resto da divisão pode ser números quebrados (ex.: 11/20 = 0,55). Não existe uma página de número 0,55, então arredondamos para cima, para dar um número inteiro.

2021-07-23 05:14 UTC, Annalgc commented on src/services/characterInfo.js
> +  return { results }
Opa! Falta de atenção e mania de abrir e fechar chaves. Obrigada pelo feedback!

2021-07-23 05:16 UTC, Annalgc commented on src/components/ComicItem/index.jsx
> +  const datesFind = (dates) => {
Beleza! Vou colocar mais em prática esse modelo mais curto nas funções que possuem retorno direto.

2021-07-23 05:30 UTC, Annalgc commented on src/pages/Profile/index.jsx
> +  }, [])
Opa! Foi mal, falta de atenção de novo..

2021-07-23 05:30 UTC, Annalgc commented on src/pages/Profile/index.jsx
> +          setTotalPerPage(Math.ceil(response.total / 20))
Neste caso, suponhamos que existe uma sobra de conteúdo a ser exibido, como estamos fazendo uma divisão, dependendo da quantidade de conteúdos, o resto da divisão pode ser números quebrados (ex.: 11/20 = 0,55). Não existe uma página de número 0,55, então arredondamos para cima, para dar um número inteiro.

2021-07-23 05:33 UTC, Annalgc commented on src/styles/globalStyles.js
> +export const Container = createGlobalStyle`
Hum.. Agora me deixou dúvidas. 😵

2021-07-23 05:43 UTC, Annalgc commented on src/pages/Profile/index.jsx
> +        .catch(error => {
Concordo! Muito boa colocação, acabei criando um `alert()`. Obrigada pelo feedback!

2021-07-23 05:43 UTC, Annalgc commented on src/pages/Profile/index.jsx
> +          console.log('erro: ', error)
Concordo! Muito boa colocação, acabei criando um `alert()`. Obrigada pelo feedback!

2021-07-23 14:45 UTC, Annalgc commented on src/styles/globalStyles.js
> +export const GlobalStyle = createGlobalStyle`
Beleza! Tive dúvidas quanto a isso, porque encontrei projetos em que o `globalStyle` era importado no `index.js` principal do app React e outros no próprio HTML. 
Neste caso, fez sentido (na minha cabeça) transformá-lo em `.css`, para importação no HTML, está certo?

2021-07-23 14:53 UTC, Annalgc commented on src/components/Paginate/index.jsx
> +import './styles.css';
Muito bom! Tentei essa compatibilidade por conta, porém, não deu certo. Com essa "documentação" que me passou, ficou simples de aplicar, deu tudo certo. Obrigada!

2021-07-23 14:56 UTC, Annalgc commented on src/services/characterInfo.js
> +  return { results }
Aliás, um adendo.. Efetuei o teste e se o return não estiver encapsulado como objeto, não recebo retorno da API. Então, acabei deixando desta forma. Você tem outra maneira de resolver isto?

2021-07-23 16:11 UTC, Annalgc commented on src/components/ComicItem/styles.js
> +    -webkit-line-clamp: 4;
Sobre isso, para retirar o `-webkit-line-clamp`, terei de colocar novos valores como `width` e o `white-space: nowrap`. As tratativas com o responsivo será diferente, já que no `width`, usaria medidas fixas como `px`, você tem alguma ideia de como alterar isto sem ter que fazer o responsivo manualmente?

2021-07-23 16:12 UTC, Annalgc commented on src/components/ComicItem/styles.js
> +    display: -webkit-box !important;
Sobre isso, para retirar o `-webkit-line-clamp`, terei de colocar novos valores como `width` e o `white-space: nowrap`. As tratativas com o responsivo será diferente, já que no `width`, usaria medidas fixas como `px`, você tem alguma ideia de como alterar isto sem ter que fazer o responsivo manualmente?

2021-07-29 17:25 UTC, hurick commented on public/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
@Annalgc bem massa mesmo o Google Fonts estar fazendo isso, principalmente pelo impacto causado no tempo pra primeiro render.

Além de fontes, tem como fazer isso com outros tipos de CSS, principalmente os que usam CDN. Vale bastante a pena dar uma caçada nisso.

2021-07-29 17:25 UTC, hurick commented on .env.example
> +REACT_APP_PUBLIC_KEY = '2244a307f79a1950202dabda8b4cdb17'
@Annalgc tranquilo então 👍🏻

2021-07-29 17:30 UTC, hurick commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
@Annalgc resumidamente, o `robots.txt` é um arquivo para ajudar os crawlers dos motores de busca como Google, por exemplo. Nesse arquivo você pode adicionar várias regrinhas pra guiá-los aos destinos corretos.

2021-07-29 17:32 UTC, hurick commented on public/manifest.json
> +{
@Annalgc é basicamente isso mesmo. Esse arquivo normalmente é utilizado para PWAs e mobile em geral.

2021-07-29 17:37 UTC, hurick commented on src/components/Cover/index.jsx
> +export const Cover = (props) => {
@Annalgc na verdade `props` é um objeto dinâmico e nesse caso você só está fazendo um destructuring dele, transformando cad atributo em um novo objeto completo.

2021-08-06 14:37 UTC, hurick approved these changes
@Annalgc PR aprovada.

2021-08-07 17:07 UTC, merged